blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    # path('post/<int:pk>/delete/', views.post_delete, name='post_delete')
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('home.urls')),
    path('polls/', include('polls.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

### Generic view (class-based view)
urlpatterns=[
    path('', views.IndexView.as_view(), name='index'),
# ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
# ex: /polls/5/results.
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
# ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

# urlpatterns=[
#     # ex: /polls/
#     path('', views.index, name='index'),
#     # ex: /polls/5/
#     path('<int:question_id>/', views.detail, name='detail'),
#     # ex: /polls/5/results
#     path('<int:question_id>/results/', views.results, name='results'),
#     # ex: /polls/5/vote/
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date=models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes=models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse
from django.template import loader
from django.http import Http404
from django.views import generic


### Generic View (class-based views)
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
# # Create your views here.
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#    # output = ', '.join([q.question_text for q in latest_question_list])
#    # return HttpResponse(output)
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'polls/index.html', context)
#
# def detail(request, question_id) :
#     # return HttpResponse("You're looking at question %s." % question_id)
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})
#
# def results(request, question_id):
#     #response = HttpResponse("You're looking at the results of question %s." % question_id)
#     #return response
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    # return HttpResponse("You're voting on question %s." % question_id)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {'question':question, 'error_message': "You didn't select a choice."})
    else:
        selected_choice.votes += 1
        selected_choice.save()

    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>2OO5938</title>
</head>
<body>
{% extends 'base.html' %}

{% block title %}
    Polls Detail
{% endblock %}
{% block content %}
<h1>{{question.question_text}}</h1>
{% if error_message %}
    <p><strong>{{error_message}}</strong></p>

{% endif%}

<form action="{% url 'polls:vote' question.id %}" method = "post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type ="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
        <label for ="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>
{% endblock %}
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>2OO5938</title>

</head>
<body>
{% extends 'base.html' %}

{% block content %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
{% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
            {% endfor %}
        </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>2OO5938</title>

</head>
<body>
{% extends 'base.html' %}

{% block content %}

{% if question.question_text %}
    <h1>{{question.question_text}}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
        {% endfor %}
    </ul>
    {% if question %}
    <h1>{{question.question_text}}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>제발</p>
{% endif %}
{% endif %}


<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

<br>
<br>

<a href="{% url 'polls:index' %}">main</a>
{% endblock %}
</body>
</html>